### ISSUE TITLE
Extension methods off IResolveFieldContext now

### ISSUE THREAD

**Issue by benmccallum** [SimonCropp/GraphQL.Validation#184]
#### Is the feature request related to a problem

A recent [GraphQL PR](https://github.com/graphql-dotnet/graphql-dotnet/pull/1441) that was merged now means that resolvers are given the interface `IResolveFieldContext` or `IResolveFieldContext<T>` rather than the concrete type.

#### Describe the solution

We'll need to update the extension methods in this project to extend the interface instead now.
In fact, since `IResolveFieldContext<T>` inherits `IResolveFieldContext<T>`, we potentially can get rid of the duplication of the extensions.

#### Describe alternatives considered

Temporary workaround (in my own code) is to have wrapping extension methods that just internally cast to the concrete and then use the existing methods in here off that. I'm not using any different context types, so it doesn't bother me atm.

#### Additional context

N/A.

**Comment by benmccallum** [comment]
I'm not sure how easy it will be to introduce this, as it's breaking against earlier versions of GraphQL. I guess we just need to set a min. version of the GraphQL depdency.

Temporary workaround (will add wrapper methods as I find them required in my code):

```

```

**Comment by benmccallum** [comment]
I see you're only targeting the 2.4.0 version of GraphQL, I guess we'd need to jump to `3.0.0-preview-1490` (ish, would need to backtrack from there until it failed to build) to do this. I'm not sure if you want to make that commitment yet. I'd say most people would be on some version of 3.0.0-preview by now though. 

Let me know and I can whip up a PR if you'd like.

**Comment by sungam3r** [comment]
Taking into account that the core package is in "deep preview state" and commits constantly break compatibility, the question of external packages referencing graphql-dotnet is not so clear.

**Comment by benmccallum** [comment]
I'm getting a method not found for `ExecutionOptions.get_UserContext` when I'm calling `UseFluentValidation` now, which I'm not really sure how to get around, or why it's even an issue.
