### ISSUE TITLE
[Request] Lower required GraphQL version to match NuGet versions

### ISSUE THREAD

**Issue by jhoward321** [SimonCropp/GraphQL.Validation#239]
#### Is the feature request related to a problem

Currently this library requires GraphQL preview >= 1630 which is a version that is only available through the MyGet feed. Lowering this requirement will allow people to use this without adding new nuget sources. Adding new nuget sources is often times difficult with build pipelines or even disallowed in certain organizations.

#### Describe the solution

Lower minimum library version dependency.

#### Describe alternatives considered

N/A

#### Additional context

N/A

**Comment by SimonCropp** [comment]
unfortunately there are breaking changes between 1490 and 1630. best to request a new deployment of the current GraphQL  to nuget. When that happens i can update to that version

**Comment by jhoward321** [comment]
Thanks for the info. I'll request a new NuGet version instead. Thanks for the quick response
