### ISSUE TITLE
How i can change exceptions.

### ISSUE THREAD

**Issue by faketogosamogo** [SimonCropp/GraphQL.Validation#282]
Hellow.
I need the field in which the exception occurred to be written in the Path of the exception.
How can i do this?

**Comment by SimonCropp** [comment]
what have you tried?

**Comment by faketogosamogo** [comment]
when i do validation for example: RuleFor (b => b.Id) .GreaterThan (-1);
if the Id field is less than 1, then the exception is thrown inside the library and I need the Id field to be specified in the ExecutionError class in the Path field.

**Comment by SimonCropp** [comment]
can you share a failing test (via a PR) that illustrates your scenario?

**Comment by faketogosamogo** [comment]
no, you misunderstand me. if the number is less than 0, as in the example above, it throws an exception, as it should. it's just that your library generates an error in the message field, but I need the error to be generated in the path field as well. how can I do this?
