### ISSUE TITLE
Validation not firing

### ISSUE THREAD

**Issue by benmccallum** [SimonCropp/GraphQL.Validation#59]
#### Is the feature request related to a problem

I'm trying to hook up the validation as per docs but validation isn't rejecting the input and getting to my resolver. I'm not sure whether the validation is supposed to fire as part of the middleware and never get to my resolver or whether the call to `GetValidatedArgument` is the only thing that triggers the validation. 

#### Describe the solution

Update readme to make this clearer. In the meantime I'll take a look at the src for the middleware.

Cheers, and thanks for a great library I'm sure we'll get a lot of use out of.

**Comment by benmccallum** [comment]
Hmm, I see that the middleware doesn't really do anything other than wrap the execution of the resolver in a catch that can then append the errors to the graph response. 

Good to know as an approach though for my own work, might look at doing something similar for some of our own uses.

Anyway, looks like the magic is really just behind the GetValidatedArgument call, which I guess is fair enough. I'm sure you've thought of this all before, but is there no way to validate all arguments in the request as part of the middleware?

**Comment by benmccallum** [comment]
On an unrelated matter, I just noticed that the `GetValidatedArgument` extension is in the `GraphQL` namespace but the core framework's `GetArgument` is under `GraphQL.Types` so then we have to add the root namespace. No biggy, but I wonder if it'd be worth changing. Would be a major version bump though which would be painful haha

**Comment by SimonCropp** [comment]
re `GraphQL.Types` i would prefer graphql was changed to have top level apis like `GetArgument` to be in the  `GraphQL`. the `.Types` suffix adds no value.

**Comment by SimonCropp** [comment]
> Update readme to make this clearer

happy to accept a PR for that

**Comment by SimonCropp** [comment]
> I'm sure you've thought of this all before, but is there no way to validate all arguments in the request as part of the middleware?

i tried really hard to find a way, but as yet: no not that i could find
