### ISSUE TITLE
Validation on non-object argument types

### ISSUE THREAD

**Issue by benmccallum** [SimonCropp/GraphQL.Validation#60]
#### Is the feature request related to a problem

I imagine there will be scenarios where we will want to validate an argument (or multiple arguments) at the root level of a query field. This library is awesome, but obviously has the limitation that everything needs to be behind an InputGraphType, aligned with a fluent IValidator, that can then be fired when the arg is requested in the resolver.

#### Describe the solution

Similar to how the dotnet-graphql/server has an Authorization project and each field can be annotated with an `.AuthorizeWith(...)`, could we have something like that as an extension method off argument declarations in fields? 

It would I guess add the validator behind a cache (like the existing type validator cache) for retrieval when needed, perhaps keyed by `type:argumentName` and then could be retrieved and fired in the `context.GetValidatedArgument<T>(...)` you've already implemented.

#### Describe alternatives considered

It could be that basic scalar validation by GraphQL-dotnet given it's typed to some degree is enough. I'm trying to think of concrete examples where I'd need this in a query and not a mutation. Perhaps something like a query that looks up users by email, and you'd want to ensure that the string arg of the email is actually even an email before you go deep into resolving and down into your app layers.

Obviously I could wrap all my query args in an input object, but I'm not sure I wanna do that. I use GitHub's api as a bit of a best practise, and they don't do that for all their queries, all the args at root-level on the fields.

**Comment by SimonCropp** [comment]
how would you express validations if u dont use the fluent API?

**Comment by SimonCropp** [comment]
bump

**Comment by benmccallum** [comment]
Sorry, been a busy week. 

Ah, I might not fully understan the question but here goes...
`IValidator<T>` doesn't specify that `T` is a class, so you could set up your validator as always (see below) and then off the argument declaration on the field, we could have an extension method like `.ValidateWith<StarRatingValidator>()` that registers it for that field.

```
    public class StarRatingValidator : AbstractValidator<int>
    {
        public PhoneNumberValidator()
        {
            RuleFor(x => x).InclusiveBetween(1, 5).;
        }
    }
```

**Comment by SimonCropp** [comment]
so happy to close this one?
