### ISSUE TITLE
Unable to resolve the Validator

### ISSUE THREAD

**Issue by amcgrawww** [SimonCropp/GraphQL.Validation#658]
Greetings,

I just cloned the code and when running it, I get the following error:

`System.InvalidOperationException: 'Cannot resolve scoped service 'MyInputValidator' from root provider.'`

![image](https://user-images.githubusercontent.com/107584736/173923495-e5718a47-e3cd-4444-b3e7-35ff0a323b6e.png)

I'm on the latest SDK (6.0.301) as specified in global.json

**Comment by SimonCropp** [comment]
can u share a failing unit test in a PR

**Comment by amcgrawww** [comment]
Hi, everything works fine when using `dotnet run` (and I cannot reproduce with a failing unit test), but I get the above error when debugging `SampleWeb` with VisualStudio, so I guess it's an environment problem and not the project itself.

Issue can be closed
